server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loan_disbursement
    username: loan_app
    password: loan_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # Use 'update' for development, 'validate' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 60000
    cache:
      key-prefix: loan-disbursement

logging:
  level:
    com.bankplus.disbursement: DEBUG
    org.springframework.web: DEBUG
