services:
  postgres:
    image: postgres:15
    container_name: loan-postgres
    environment:
      POSTGRES_DB: loan_disbursement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loan-network

  redis:
    image: redis:7-alpine
    container_name: loan-redis
    ports:
      - "6379:6379"
    networks:
      - loan-network

  data-ingestion-service:
    build:
      context: ../backend/data-ingestion
      dockerfile: Dockerfile
    container_name: loan-data-ingestion-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loan_disbursement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    networks:
      - loan-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: loan-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8081/api
    depends_on:
      - data-ingestion-service
    networks:
      - loan-network

volumes:
  postgres_data:

networks:
  loan-network:
    driver: bridge