server:
  port: 8081

spring:
  application:
    name: data-ingestion-service
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  datasource:
    url: jdbc:postgresql://postgres:5432/loan_disbursement
    username: loan_user
    password: loan_password
    driver-class-name: org.postgresql.Driver
  redis:
    host: redis
    port: 6379
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.bankplus: DEBUG
    org.springframework.web: DEBUG

forecasting:
  service:
    url: http://loan-forecasting-service:8082 

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 

file:
  input-dir: backend/data/Input/
  forecast-dir: backend/data/forecast/ 