server:
  port: 8081

spring:
  application:
    name: data-ingestion-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/loan_disbursement
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.bankplus.data_ingestion: DEBUG
    com.bankplus.data_ingestion.service.CsvProcessingService: DEBUG 

forecasting:
  service:
    url: http://loan-forecasting-service:8082 