server:
  port: 8081

spring:
  application:
    name: data-ingestion-service
  
  datasource:
    url: jdbc:postgresql://loan-postgres:5432/loan_disbursement
    username: loan_user
    password: loan_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.bankplus: DEBUG
    org.springframework.web: DEBUG

forecasting:
  service:
    url: http://loan-forecasting-service:8082 