server:
  port: 8082

spring:
  application:
    name: forecasting-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_disbursement
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

logging:
  level:
    com.bankplus.forecasting_service: DEBUG
    org.springframework.web: DEBUG 