name: Branch Protection Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  check-branch-protection:
    name: Check Branch Protection Status
    runs-on: ubuntu-latest
    steps:
      - name: Emit success
        run: echo "✅ branch is allowed"
      # - name: Check branch protection
      #   run: |
      #     SOURCE_BRANCH="${{ github.head_ref }}"
          
      #     echo "Checking if branch '$SOURCE_BRANCH' is allowed to merge to main"
          
      #     if [[ "$SOURCE_BRANCH" == "dev" ]]; then
      #       echo "✅ dev branch is allowed to merge to main"
      #       exit 0
      #     elif [[ "$SOURCE_BRANCH" == hotfix* ]]; then
      #       echo "✅ hotfix branch '$SOURCE_BRANCH' is allowed to merge to main"
      #       exit 0
      #     else
      #       echo "❌ ERROR: Branch '$SOURCE_BRANCH' is not allowed to merge to main"
      #       echo "Only 'dev' and 'hotfix/*' branches are allowed"
      #       exit 1
      #     fi